@auth_final_101_HostAddress = http://localhost:5285

@auth_final_101_Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYwY2YyMmRlLWNmOTYtNDNmNi1hYzhjLTM3MjYyYzNkNTZmNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJBIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiQUBBLmMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzA5OTgyNTExLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1Mjg1IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTI4NSJ9.BmCWRvFlVgQqtmkkJh3UxJWbBkxiHu-LUociC8h-VPM"


GET {{auth_final_101_HostAddress}}/weatherforecast/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ0MWE2ZmRlLTllNDgtNDc0MS1hYTdlLTFlMzQ0MmY0YWQ3ZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJTIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiREBkIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTcwOTk4MjY4OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTI4NSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUyODUifQ.xmDX5eAOahESLV91xYely2zL_VNQyFFAirG75bbi57w
###
